# Generated by Django 4.0.1 on 2022-01-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('price', models.FloatField()),
                ('image_URL', models.TextField(max_length=4056)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=40)),
                ('balance', models.FloatField()),
                ('autor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.course')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='autor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.user'),
        ),
    ]
